import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { NAVBAR_Body } from "@/components/NAVBAR_Body";
import { FOOTER_Body } from "@/components/FOOTER_Body";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AEDL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NAVBAR_Body />
        {children}
        <FOOTER_Body />
      </body>
    </html>
  );
}
